### ISSUE TITLE
Some problems about codes

### ISSUE THREAD

**Issue by asdcaszc** [sen-mao/StyleDiffusion#2]
I cannot run this requirments.txt. Maybe some libraries version is not suitable for my computer. Through downloading manually, I find you miss 'pandas' package and here is a strange problem. The possible reason is that you use your local anaconda path. I don't know whether if this part of the codes needs to be modified or removed.

Namespace(end_case=2, from_case=1, is_1word=0, is_train=False, prompts_path='./d                                                                                                                                   ata/stylediffusion_editing.csv', save_path='stylediffusion-images', sd_version='                                                                                                                                   sd_1_4')
|----- case_number:1, target: "black and white tiger playing red ball on black c                                                                                                                                   arpet". -----|
sh: 1: /home/yaxing/anaconda3/envs/prompt2prompt/bin/python: not found

**Comment by sen-mao** [comment]
You need to replace /home/yaxing/anaconda3/envs/prompt2prompt/bin/python in https://github.com/sen-mao/StyleDiffusion/blob/b1cadb011712544cbe58a9154549e84703294d9e/stylediffusion_csv.py#L58 with the path to python in your environment.
