### ISSUE TITLE
Some issues when running the code

### ISSUE THREAD

**Issue by yomin-y** [sen-mao/StyleDiffusion#4]
![image](https://github.com/sen-mao/StyleDiffusion/assets/55073040/4c9837e3-880b-4de6-8140-6c6a68385e0d)
thanks for your great work! However, I encounter this bug when running the code. It seems like the attention_store is Empty with no keys in it. WHEN I set the parameter blend_word from "[('dog',), ('tiger',)]" to None, the code successfully runs. So, the issue encounters when the attentions blend. Have you ever had this problem before? and what should I do to fix it. Thanks a lot.

**Comment by sen-mao** [comment]
check if the version you use is diffusers==0.8.0

**Comment by yomin-y** [comment]
> check if the version you use is diffusers==0.8.0

It works, thanks a lot.
