### ISSUE TITLE
Why did my style transfer fail?

### ISSUE THREAD

**Issue by ScuLancer** [sen-mao/StyleDiffusion#6]
hello,I have the question about the code
This is my Inferential code
python stylediffusion.py --is_train '' --index 1 --prompt "a tent in forest" \
                         --image_path "./example_images/a tent in forest.jpg" \
                         --target "a tiger in forest" \
                         --tau_v [.2,] --tau_c [.6,] --tau_s [.6,] --tau_u [.5,] \
                         --blend_word "[('tent',), ('tiger',)]" --eq_params "[('tiger',), (2,)]" --edit_type Replacement
![image](https://github.com/sen-mao/StyleDiffusion/assets/158799988/cc6e29c4-ba58-4b3e-8f20-a03f7eef27d7)
But you can see that I failed the style Transfer. I want to know why.Thank you very much!

**Comment by sen-mao** [comment]
Hi, you can try the code in p2plus catalogue:

```
python text_inv_w_p2plus.py --image_path "./example_images/a tent in forest.jpg" \
                            --prompt "a tent in forest" --target "a tiger in forest" \
                            --tau_c "[.6,]"  --tau_s "[.6,]"  --tau_u "[.0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1.,]" \
                            --blend_word "[('tent',), ('tiger',)]"  --eq_params "[('tiger',), (2,)]" \
                            --edit_type Replacement
```
